# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1
set_property target_language Verilog [current_project]
set_param project.compositeFile.enableAutoGeneration 0
add_files c:/Users/Fran/Desktop/test_31.coe
add_files c:/Users/Fran/Desktop/prg_blank.coe
add_files c:/Users/Fran/Desktop/dmem32.coe
add_files D:/Vivado/project_cpu/project_cpu.runs/dist_mem_gen_0_synth_1/dist_mem_gen_0.dcp
set_property used_in_implementation false [get_files D:/Vivado/project_cpu/project_cpu.runs/dist_mem_gen_0_synth_1/dist_mem_gen_0.dcp]
set_property use_blackbox_stub false [get_files D:/Vivado/project_cpu/project_cpu.runs/dist_mem_gen_0_synth_1/dist_mem_gen_0.dcp]
add_files D:/Vivado/project_cpu/project_cpu.runs/dist_mem_gen_1_synth_1/dist_mem_gen_1.dcp
set_property used_in_implementation false [get_files D:/Vivado/project_cpu/project_cpu.runs/dist_mem_gen_1_synth_1/dist_mem_gen_1.dcp]
set_property use_blackbox_stub false [get_files D:/Vivado/project_cpu/project_cpu.runs/dist_mem_gen_1_synth_1/dist_mem_gen_1.dcp]
read_verilog {
  D:/Vivado/project_cpu/project_cpu.srcs/sources_1/imports/MinySys-Int/wtd16.v
  D:/Vivado/project_cpu/project_cpu.srcs/sources_1/imports/MinySys-Int/uart16.v
  D:/Vivado/project_cpu/project_cpu.srcs/sources_1/imports/MinySys-Int/pwm16.v
  D:/Vivado/project_cpu/project_cpu.srcs/sources_1/imports/MinySys-Int/memorio.v
  D:/Vivado/project_cpu/project_cpu.srcs/sources_1/imports/MinySys-Int/led16.v
  D:/Vivado/project_cpu/project_cpu.srcs/sources_1/imports/MinySys-Int/key16.v
  D:/Vivado/project_cpu/project_cpu.srcs/sources_1/imports/MinySys-Int/ioread.v
  D:/Vivado/project_cpu/project_cpu.srcs/sources_1/imports/MinySys-Int/init32.v
  D:/Vivado/project_cpu/project_cpu.srcs/sources_1/imports/MinySys-Int/Ifetc32.v
  D:/Vivado/project_cpu/project_cpu.srcs/sources_1/imports/MinySys-Int/Idecode32.v
  D:/Vivado/project_cpu/project_cpu.srcs/sources_1/imports/MinySys-Int/Executs32.v
  D:/Vivado/project_cpu/project_cpu.srcs/sources_1/imports/MinySys-Int/dmemory32.v
  D:/Vivado/project_cpu/project_cpu.srcs/sources_1/imports/MinySys-Int/ctc16.v
  D:/Vivado/project_cpu/project_cpu.srcs/sources_1/imports/MinySys-Int/control32.v
  D:/Vivado/project_cpu/project_cpu.srcs/sources_1/imports/MinySys-Int/minisys.v
  d:/Vivado/project_cpu/project_cpu.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0_stub.v
  d:/Vivado/project_cpu/project_cpu.srcs/sources_1/ip/dist_mem_gen_1/dist_mem_gen_1_stub.v
}
read_xdc dont_buffer.xdc
set_property used_in_implementation false [get_files dont_buffer.xdc]
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Vivado/project_cpu/project_cpu.data/wt [current_project]
set_property parent.project_dir D:/Vivado/project_cpu [current_project]
synth_design -top minisys -part xc7a100tcsg324-1
write_checkpoint minisys.dcp
report_utilization -file minisys_utilization_synth.rpt -pb minisys_utilization_synth.pb
